http_bind_addr = "127.0.0.1:8080"
request_body_limit_bytes = 52428800
sse_keep_alive_ms = 10000

[[models]]
model_name = "rwkv-7.2b-g1e"
model_cfg = "rwkv-lm-7.2b"
weights_path = "/home/caizus/Weights/rwkv-rs__rwkv-rs-g1/rwkv7-g1e-7.2b-20260301-ctx8192.bpk"
tokenizer_vocab_path = "../../assets/rwkv_vocab_v20230424.txt"
device_type = 0
device_ids = [1, 2, 3]
max_batch_size = 128
max_context_len = 8192
paragraph_len = 16
decode_first = true
