http_bind_addr = "0.0.0.0:8080"
request_body_limit_bytes = 52428800
sse_keep_alive_ms = 10000

[[models]]
model_name = "rwkv7-0.1b-g1d"
model_cfg = "rwkv-lm-0.1b"
weights_path = "/home/caizus/Weights/rwkv-rs__rwkv-rs-g1/rwkv7-g1d-0.1b-20260129-ctx8192.bpk"
tokenizer_vocab_path = "../../assets/rwkv_vocab_v20230424.txt"
device_type = 0
device_ids = [0]
max_batch_size = 4096
max_context_len = 8192
paragraph_len = 16
decode_first = true

[[models]]
model_name = "rwkv7-0.4b-g1d"
model_cfg = "rwkv-lm-0.4b"
weights_path = "/home/caizus/Weights/rwkv-rs__rwkv-rs-g1/rwkv7-g1d-0.4b-20260210-ctx8192.bpk"
tokenizer_vocab_path = "../../assets/rwkv_vocab_v20230424.txt"
device_type = 0
device_ids = [1]
max_batch_size = 4096
max_context_len = 8192
paragraph_len = 16
decode_first = true

[[models]]
model_name = "rwkv7-1.5b-g1e"
model_cfg = "rwkv-lm-1.5b"
weights_path = "/home/caizus/Weights/rwkv-rs__rwkv-rs-g1/rwkv7-g1e-1.5b-20260309-ctx8192.bpk"
tokenizer_vocab_path = "../../assets/rwkv_vocab_v20230424.txt"
device_type = 0
device_ids = [2]
max_batch_size = 2048
max_context_len = 8192
paragraph_len = 16
decode_first = true

[[models]]
model_name = "rwkv7-2.9b-g1e"
model_cfg = "rwkv-lm-2.9b"
weights_path = "/home/caizus/Weights/rwkv-rs__rwkv-rs-g1/rwkv7-g1e-2.9b-20260312-ctx8192.bpk"
tokenizer_vocab_path = "../../assets/rwkv_vocab_v20230424.txt"
device_type = 0
device_ids = [3]
max_batch_size = 1024
max_context_len = 8192
paragraph_len = 16
decode_first = true
