model_type = "sequence_embedding"

num_cells = 12
vocabulary_size = 5
embedded_dim = 512
num_heads = 8
channel_mix_dim_scale = 4
dropout_prob = 0.01

with_token_shift = true
with_deep_embed_att = false
with_deep_embed_ffn = false