experiment_name = "dna"

dataset_base_path = "/public/home/ssjxzkz/Datasets/geno/ani"
filename_without_extensions = "paired"
random_seed = 42

train_stage = "pretrain"

num_nodes = 1
num_devices_per_node = 1
batch_size_per_device = 64
num_dataset_repeats = 1
context_length = 1024

optimizer = "adam_w"
learning_rate_start = 1e-4
learning_rate_end = 1e-5
warmup_steps = 0
weight_decay = 0.001
gradient_clip_val = 1.0
grad_checkpoint = true

level = "warn"
use_tui = false
upload_to_wandb = false
wandb_api_key = "0846134e1a784dcd3495320a5ab21a73d2377a1d"
wandb_entity_name = "rhineai"
wandb_project_name = "dna"